name: travel_app
description: "A Klook-style Flutter travel app UI clone."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  easy_localization: ^3.0.8
  shared_preferences: ^2.3.2
  carousel_slider: ^5.0.0
  http: ^1.2.2
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  intl_utils: ^2.8.5

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/banner.jpg
    - assets/tour1.jpg
    - assets/tour2.jpg
    - lib/l10n/

  fonts:
    - family: Roboto
      fonts:
        - asset: fonts/Roboto-Regular.ttf
        - asset: fonts/Roboto-Medium.ttf
          weight: 500
        - asset: fonts/Roboto-Bold.ttf
          weight: 700
